debug: true

registry:
  identity: "local.test"
  etcd:
    endpoints: [ "10.11.21.50:12379","10.11.21.50:12381","10.11.21.50:12383" ]

management:
  address:
  port: 9999
  enabled: true
  secret: "123456"
  ip_whitelist: "" # e.g. "127.0.0.1,192.168.1.2"